# Ip should be the ip of your server and not just 127.0.0.1 or localhost.
# You have to restart your server after editing the ip or port.
ip: "e.x.a.m.p.l.e"
port: 25564

# If the player is forced to enable the resourcepack
forced: true

# The resourcepacks that should be applied when the player joins.
# Example:  default: ["skyblock-resourcepack", "overall"]
default: ["default"]

####################
#     Language     #
####################

# Prompt shown to the player when they are asked to accept the resourcepack
error_noplayer: "§cWe can not find the player named {player}"
error_noperms: "§cYou are missing the permission {permission} todo this."
error_nopack: "§cYou need to provide a resourcepack name"
error_invalidcommand: "§cUnknown sub command"
message_prompt: "No prompt provided"
message_update: "§aAn update is available for the resourcepack. Run /resourcepack to update."
message_startupdate: "§7Starting to load the files..."
message_removeall: "Forcing player to remove resourcepack..."
message_needname: "You need to provide a name of the resourcepack you want to load"
message_download_failed: "§cWe where unable to download the resourcepack."
message_download_complete: "§aYou are now using the resourcepack"
message_downloading: "§7We are downloading your resourcepacks..."
message_listupdated: "§aYou have updated your resourcepack preferences. Be sure to run §l/rp update §ato active them."