name: SimpleResourcepack
version: '${version}'
main: dev.thesheep.simpleresourcepack.SimpleResourcepack
api-version: '${apiVersion}'
commands:
  resourcepack:
    usage: /resourcepack
    aliases: [rp, pack]
