name: SimpleResourcepack
version: '${project.version}'
main: dev.thesheep.simpleresourcepack.SimpleResourcepack
api-version: '1.20'
commands:
  resourcepack:
    usage: /resourcepack
    aliases: [rp, pack]
